### ISSUE TITLE
how to use custom https://pay.mollie.nl/checkout/v2/css/global.css ?

### ISSUE THREAD

**Issue by pedalracer** [mollie/PrestaShop#126]
I need to know how to use custom css for global.css.

I tried via {CSS}mollie_global_ito.css in module but to no avail.

**Comment by margud** [comment]
This feature will be fixed in next 3.4.4 release but if you want to manually fix it fallow this steps.
1)Create custom_css.tpl in views/templates/front/ and paste this line. 
<link rel="stylesheet" href="{$custom_css}" type="text/css" media="all">
2) go to mollie.php file and find function hookDisplayHeader() line: 2201.
There you will need to change everything to this:
        $this->addCSSFile($this->_path.'views/css/front.css');
        $this->context->controller->addJS($this->getPathUri() . 'views/js/apple_payment.js');

        $this->context->smarty->assign(array(
            'custom_css'   => Configuration::get(static::MOLLIE_CSS),
        ));
        return $this->display(__FILE__, 'views/templates/front/custom_css.tpl');


After this you should be good to go. Inserting links to css file will work on front-office.
