### ISSUE TITLE
[PrestaShop] Fatal error in module file :/var/www/modules/mollie/vendor/firstred/mollie-api-php/src/Exceptions/ApiException.php:

### ISSUE THREAD

**Issue by semammerlaan** [mollie/PrestaShop#148]
Cannot proces payments or access plugin settings in admin, this is the error message i receive when open de plugin page in the admin dashboard:

`[PrestaShop] Fatal error in module file :/var/www/modules/mollie/vendor/firstred/mollie-api-php/src/Exceptions/ApiException.php:
Uncaught exception 'Mollie\Api\Exceptions\ApiException' with message 'Error executing API call (: ): ' in /var/www/modules/mollie/vendor/firstred/mollie-api-php/src/Exceptions/ApiException.php:101 Stack trace: #0 /var/www/modules/mollie/vendor/firstred/mollie-api-php/src/Exceptions/ApiException.php(77): Mollie\Api\Exceptions\ApiException::createFromResponse(Object(Hough\Psr7\Response)) #1 /var/www/modules/mollie/vendor/firstred/mollie-api-php/src/MollieApiClient.php(329): Mollie\Api\Exceptions\ApiException::createFromRequestException(Object(Mollie\Api\Exceptions\RequestException)) #2 /var/www/modules/mollie/vendor/firstred/mollie-api-php/src/MollieApiClient.php(292): Mollie\Api\MollieApiClient->performHttpCallToFullUrl('GET', 'https://api.mol...', NULL) #3 /var/www/modules/mollie/vendor/firstred/mollie-api-php/src/Endpoints/EndpointAbstract.php(132): Mollie\Api\MollieApiClient->performHttpCall('GET', 'methods?resourc...') #4 /var/www/modules/mollie/vendor/firstred/mollie-api-php/src/Endpoints/MethodEndpoint.p`

### Environment
* PrestaShop version: 1.6.1.3
* Mollie module version: 3.5.0
* PHP version: 5.5.3

**Comment by margud** [comment]
There were some issues with new changes for PS1.6 version. Could you try installing new [3.5.1 pre-release ](https://github.com/mollie/PrestaShop/releases/tag/3.5.1). If you still get this issue tell us and we will investigate it further.

**Comment by semammerlaan** [comment]
Thanks! I can access the plugin settings but cannot retrieve payment methods:

![image](https://user-images.githubusercontent.com/6170697/70977054-6d18e300-20ad-11ea-8367-d58c0f745fe0.png)

![image](https://user-images.githubusercontent.com/6170697/70977044-68542f00-20ad-11ea-8d75-f7c042d33ee0.png)

**Comment by margud** [comment]
Are you sure you are using correct API key? If your API key doesn't have any available payments than this message is correct. You can test it with this key: test_T4BK7hfaVDc6eUCMr6f4qVaD6WWrqJ
If it works something is wrong with your key. We will see what we can do if it still doesn't work.

**Comment by iXeQuta** [comment]
I have also tried different API keys but the errors keep coming back. I have reinstalled the plugin several times to no avail.

![Screenshot 2019-12-17 at 10 29 08](https://user-images.githubusercontent.com/36068234/70983164-8a9f7a00-20b8-11ea-9fa7-093004dffeff.png)

**Comment by margud** [comment]
We will see what we can do. Maybe you could sand me your ftp to
marius.gudauskis@invertus.eu
This way i could check what is wrong with it

**Comment by jhalfkan** [comment]
I have the same bug since 5 days.
If, i reset the module i'm able to add an API key.
When i save the setting with an api key (live or test), i have the error

`Fatal error: Uncaught exception 'Mollie\Api\Exceptions\ApiException' with message 'Error executing API call (: ): ' in /var/www/modules/mollie/vendor/firstred/mollie-api-php/src/Exceptions/ApiException.php:101 Stack trace: #0 /var/www/modules/mollie/vendor/firstred/mollie-api-php/src/Exceptions/ApiException.php(77): Mollie\Api\Exceptions\ApiException::createFromResponse(Object(Hough\Psr7\Response)) #1 /var/www/modules/mollie/vendor/firstred/mollie-api-php/src/MollieApiClient.php(329): Mollie\Api\Exceptions\ApiException::createFromRequestException(Object(Mollie\Api\Exceptions\RequestException)) #2 /var/www/modules/mollie/vendor/firstred/mollie-api-php/src/MollieApiClient.php(292): Mollie\Api\MollieApiClient->performHttpCallToFullUrl('GET', 'https://api.mol...', NULL) #3 /var/www/modules/mollie/vendor/firstred/mollie-api-php/src/Endpoints/EndpointAbstract.php(132): Mollie\Api\MollieApiClient->performHttpCall('GET', 'methods?resourc...') #4 /var/www/modules/mollie/vendor/firstred/mollie-api-php/src/Endpoints/MethodEndpoint.p in /var/www/modules/mollie/vendor/firstred/mollie-api-php/src/Exceptions/ApiException.php on line 101
[PrestaShop] Fatal error in module file :/var/www/modules/mollie/vendor/firstred/mollie-api-php/src/Exceptions/ApiException.php:
Uncaught exception 'Mollie\Api\Exceptions\ApiException' with message 'Error executing API call (: ): ' in /var/www/modules/mollie/vendor/firstred/mollie-api-php/src/Exceptions/ApiException.php:101 Stack trace: #0 /var/www/modules/mollie/vendor/firstred/mollie-api-php/src/Exceptions/ApiException.php(77): Mollie\Api\Exceptions\ApiException::createFromResponse(Object(Hough\Psr7\Response)) #1 /var/www/modules/mollie/vendor/firstred/mollie-api-php/src/MollieApiClient.php(329): Mollie\Api\Exceptions\ApiException::createFromRequestException(Object(Mollie\Api\Exceptions\RequestException)) #2 /var/www/modules/mollie/vendor/firstred/mollie-api-php/src/MollieApiClient.php(292): Mollie\Api\MollieApiClient->performHttpCallToFullUrl('GET', 'https://api.mol...', NULL) #3 /var/www/modules/mollie/vendor/firstred/mollie-api-php/src/Endpoints/EndpointAbstract.php(132): Mollie\Api\MollieApiClient->performHttpCall('GET', 'methods?resourc...') #4 /var/www/modules/mollie/vendor/firstred/mollie-api-php/src/Endpoints/MethodEndpoint.p`

**Environment**
- PrestaShop version: 1.6.1.24
- Mollie module version: 3.4.5

**Comment by margud** [comment]
API error handle changed and we added its handle in 3.5.1 pre-release. But i m not sure why your api key doesnt work. This error is throw when api key is invalid. What php version are you using? And did your api key worked fine before that?

**Comment by jhalfkan** [comment]
The api key worked fine before that.
Php version is 5.6

**Comment by semammerlaan** [comment]
@margud did you find something? For 5 days we cannot accept ideal payments. It's becoming critical.

**Comment by margud** [comment]
Just found out that Mollie renewed SSL certificate and now every one needs to update their certificate. For more details: https://aimeos.org/help/viewtopic.php?t=2587&p=10375

**Comment by szczepan358** [comment]
I have exactly the same problem, how to solve it ?

**Comment by margud** [comment]
You need to update SSL certificate in your server.

**Comment by szczepan358** [comment]
> You need to update SSL certificate in your server.

my hoster will not do that, is is posibble to do in Direct Admin ?

**Comment by margud** [comment]
I don't think it's possible. Mollie requires to update SSL certificate in your server for security reasons.
