### ISSUE TITLE
When stock is negative payment not set

### ISSUE THREAD

**Issue by basemedia** [mollie/PrestaShop#160]
### Expected behavior
Status set to " payment accepted"

### Actual behavior
When stock is in negative. Status is not set to payment accepted.
Information of payment is also not set in field or it's set double.

![Screenshot 2020-03-26 at 16 10 29](https://user-images.githubusercontent.com/1645341/77662603-5f141180-6f7c-11ea-9da5-6a341b719f61.png)

### Steps to reproduce the behavior
Place order (stock allowed to go to negative)

### Environment
* PrestaShop version: 1.7.6.2
* Mollie module version: 3.3.5
* PHP version: 7.2

**Comment by SimonasB88** [comment]
Hello @basemedia , thank you for message, 

We will take a look and update you ASAP!

Best Regards.

**Comment by SimonasB88** [comment]
Hello dear @basemedia , 
Could you please upgrade the module with the newest release https://github.com/mollie/PrestaShop/releases/tag/3.5.5 , and reproduce the issue once again, and let us know?

Thank you.

**Comment by basemedia** [comment]
Hello,

We have this version installed.

Luke

**Comment by SimonasB88** [comment]
Hey,

You pressed Upgrade on the module, and while reproducing the issue remains the same, yes?

If issue still exists, in order to investigate your issue and help you efficiently, can you send support@invertus.eu an access to your backoffice with its url and a FTP access to your store:

URL back office:
login back office:
password back office:


FTP host:
FTP login:
FTP password:
FTP port:

Developer will check it and let you know.

Best Regards.

**Comment by basemedia** [comment]
Is this issue fixed in the new release? Will you upload a .zip file?

**Comment by SimonasB88** [comment]
Hello @basemedia , thank you for the interest in module,

Yes, it is fixed in the newest release. This option is functionally working OK now from Prestashop 1.6 version.

If you haven't been able to check the newest version, please navigate to the Release page:
https://github.com/mollie/Prestashop/releases

Have a great day.
Best Regards.

Invertus Support Team
