### ISSUE TITLE
When status is changed after payment no email is send to customer 

### ISSUE THREAD

**Issue by Frankyet** [mollie/PrestaShop#161]
### Expected behavior
After payment with Mollie module status should be changed to payment accepted and a confirm e-mail should be send to customer, and if there is no stock the status is changed to back-order and there should be an e-mail send to customer.

### Actual behavior
After payment with Mollie module status is not changed to payment accepted and no e-mail is send to customer, and if there is no stock the status is changed to back-order but no e-mail is send to customer.

### Steps to reproduce the behavior
make an test order with an article that is out of stock and allow order product to order if there is no stock. with other payment module like PayPal it is working as it should be

### Environment
* PrestaShop version: 1.7.6.4
* Mollie module version: 3.5.5 tested on older versions  all same issue
* PHP version: 7.2

![image](https://user-images.githubusercontent.com/22242384/77819047-2426f080-70d8-11ea-81be-1594ccb906ca.png)

**Comment by SimonasB88** [comment]
Hello @Frankyet , thank you for message,

We will check this and update you ASAP!

Best Regards.

**Comment by SimonasB88** [comment]
Hello once again @Frankyet ,

We don't want to guess about this.

Could you please provide us your credentials?
In order to investigate your issue and help you efficiently, can you send us an access to your backoffice with its url and a FTP access to your store (send everything to support@invertus.eu):


URL back office:

login back office:

password back office:


FTP host:

FTP login:

FTP password:

FTP port:

Thank you.
