### ISSUE TITLE
Withhold email to merchant until order is created AND payment is received

### ISSUE THREAD

**Issue by MerijnMollie** [mollie/PrestaShop#182]
### Expected behavior
Only send a system email to the merchant when the order also has a payment (just like towards the consumer).
This can be set in the plugin settings.

### Current behavior
Merchant receives an email for orders that are not paid yet.

We'll create a setting in the backend, where email towards merchant can be set to 'Only send an email when payment is confirmed'.

### Environment
* PrestaShop version: 1.7.5.0 
* Mollie module version: 3.3.4 
* PHP version: 7.1.26

**Comment by pswaab** [comment]
Hi Merijn,

This is working perfectly in module 3.5.x but from version 4.x.x this problem exists, because an order gets created before payment is done.

Kind regards,

Patrick

**Comment by SimonasB88** [comment]
Hey guys @MerijnMollie @pswaab 

Just follow upping. You mentioned v3.x.x of the module, so, in other words, this functionality
![image](https://user-images.githubusercontent.com/29095235/87149753-7e2f7880-c2b9-11ea-9d11-a71a47021817.png)
 should be included in older versions you mean?

Best Regards.

**Comment by pswaab** [comment]
Hi @SimonasB88,

No, we mean a notification which is sent when an order is created to the merchant self.
This is a module from prestashop with a complete order overview and also shows the payment which the customer has chosen.

Regards, Patrick

**Comment by SimonasB88** [comment]
Hey @pswaab 

Will talk to the team and update you about this case 👍 

Best Regards.

**Comment by SimonasB88** [comment]
Hey guys, just follow-upping the thread,

We assume that the merchant is using “Mail alerts” which is sending him emails when a new order is created or maybe the merchant is using another module that sends emails because in BO there is no such setting to send emails when order is created.

Is this should be a custom improvement for a certain user or “Mollie” module improvement? 

Thank you.

Best Regards.

**Comment by RVanDamage** [comment]
Hi there @SimonasB88,

I think most people indeed use the "Mail alerts" module. So maybe some setting in the Mollie module could be added like:

"Only send new_order confirmation email to merchant when payment is confirmed (When using PrestaShop Mail Alerts module)"

**Comment by SimonasB88** [comment]
@RVanDamage thanks for your insight!

We will discuss with the team and we will follow up about his!

Best Regards.

**Comment by pswaab** [comment]
HI,

I still think the best option is to not create an order before payment is done.
This way all the issues we have with the new module wil be solved.

- Shopping cart is still available until order is created
- Merchant wil not receive an email of order creation
- No pending orders waiting for payment and less canceled orders

Best regards,

Patrick

**Comment by RVanDamage** [comment]
@pswaab I totally agree. However, if creating a bunch of overrides in their module is the only way of achieving this, then I understand why they have chosen for this. But I'm not sure or these overrides are needed.

Don't get me wrong, we have a few large customers depending on this "Mail alerts" new_order email function too. So we really need that merchant switch otherwise we can't upgrade from v3.5.5.

For one of those customers we actually customized the "Mail alerts" module into some version where for every email a XML file is attached for that specific order, which the employees can upload into the ERP system they work with. From there the whole shipping and everything is automated. So they can absolutely not afford to have non-paid orders in there.

**Comment by MerijnMollie** [comment]
Hi @pswaab and @RVanDamage ,

Thanks again for your input!
Currently we have the 4.07 release almost ready, which has the fix for the shopping cart issue.
Indeed, the bunch of overrides was needed, and withheld us from proper/fast new development.

As said, 4.07 will bring huge improvements and some cool new features as well.

We're also looking into this merchant-alerting issue at the same time, by adding extra filtering on the email functionality.
@RVanDamage : could you please send me a quick email on: merijn@mollie.com, so we can discuss in person how the exact setup is with your customers? I would like to learn a bit more to be able to tackle this in the best/broadest way.

Thanks!

**Comment by Maz-Invertus** [comment]
Hi @pswaab and @RVanDamage ,

Please have a look at [Mollie new 4.0.7 release](https://github.com/mollie/PrestaShop/releases/tag/4.0.7) where this issue has been fixed.
Thank you for being an active community member!

**Comment by RVanDamage** [comment]
Hi @MerijnMollie ,

The 4.07 release is looking very good so far :) Great work!

Regarding this merchant-alerting issue, this is good to hear. However, I am currently out office until august 24th. So if it's not too much to wait, I will contact you privately somewhere around that time.

**Comment by SimonasB88** [comment]
Hey everyone!
The thread is closed due the inactivity for some time.
Please raise a new ticket if it is necessary.

Have a great day!
Best Regards.
