### ISSUE TITLE
Save Shopping Bag when customer clicks back, or when Payment is canceled

### ISSUE THREAD

**Issue by MerijnMollie** [mollie/PrestaShop#183]
### Expected behavior
When a consumer clicks 'back' during payment, or payment is canceled any other way, the consumer should land back in the shopping basket, remembering customer details AND shopping bag products.

### Actual behavior
Currently, the products are not saved.

### Steps to reproduce the behavior
Create an order, go to payment, click 'back' browser, see an empty shopping bag where consumer has to re-order the products.

### Environment
* PrestaShop version: all
* Mollie module version: all

**Comment by pswaab** [comment]
Hi Merijn,

Actually the environment where this happens, is only from module 4.x.x.
Module 3.5.x and all previous modules did not have this problem, as there was no order created when not paid (just like PayPal).

Kind regards,

Patrick

**Comment by SimonasB88** [comment]
Hey guys,

Have you tried the v 4.0.6 and the "going back" action?

Please let us know the comments and if it is solved we can close the ticket.

Best Regards.

**Comment by RVanDamage** [comment]
Hi @SimonasB88,

I just tested this on 4.0.6. It turns out when you go to a payment page and use the browsers "back button" to go back, the cart will return empty indeed :( 

However when you go to a payment page, and click the actual "cancel payment" option from the chosen payment, it will redirect back to the shop, remind the cart and display a PrestaShop front-end error saying "Your payment was not successful, please try again." 
<img width="359" alt="payment-not-successful" src="https://user-images.githubusercontent.com/68848292/88530451-b0531100-d001-11ea-8a60-8dc6f5a63c99.png">

**Comment by SimonasB88** [comment]
Hey @RVanDamage thank you for your insight!

Regarding your first insight, I have tested on our pre-production v 4.0.7 PS1763 PHP 7.0 All Shops Firefox MacOS, and the browser back button is redirecting to the last step of Prestashop address choosing step. No loosing of cart data in upcoming release.

Best Regards.

**Comment by RVanDamage** [comment]
@SimonasB88 Thank you for testing!

Good to hear that this problem is now fixed in version 4.0.7 :)

Hopefully 4.0.7 will be released soon.

**Comment by Maz-Invertus** [comment]
Hi @pswaab and @RVanDamage,

Please have a look at [Mollie new 4.0.7 release](https://github.com/mollie/PrestaShop/releases/tag/4.0.7) where this issue has been fixed.
Thank you for being an active community member!

**Comment by margud** [comment]
This ticket is closed due to lack of activity for some time.
If the issue wasn’t solved please raise a new ticket and our support team will assign a developer to it.
Have a nice day.
