### ISSUE TITLE
Select multi-payment methods in 1-click

### ISSUE THREAD

**Issue by blikflits** [mollie/PrestaShop#226]
### Expected behavior

When you click on the radio button from payment method Ideal the radio button will be selected.

### Actual behavior

In version 4.0.8 and 4.0.9 you click on the radio button payment method Ideal and all the other payment method are selected too.

### Steps to reproduce the behavior

![2020-10-26 16_26_27-Supercheckout _ Wandelsok nl](https://user-images.githubusercontent.com/20137664/97192316-16d5ff80-17a8-11eb-8e4b-07271bd39124.png)

### Environment
* PrestaShop version: 1.6.1.24 
* Mollie module version: 4.0.9 
* PHP version: 7.2.32

**Comment by SimonasB88** [comment]
Hey! Thank you for the message.
Backloged for the reproduction.

Will update you soon.
Best Regards.

**Comment by SimonasB88** [comment]
Hey @blikflits could you please provide us more information? Are you using One Page Checkout probably? Or are you using custom Prestashop theme?

The default Prestashop theme PS16124 PHP 7.2 has no issues.

![Kapture 2020-10-29 at 11 47 38](https://user-images.githubusercontent.com/29095235/97552274-baa7f100-19dc-11eb-84dc-26c5829bcfef.gif)

**Comment by Goedkoopsteverf** [comment]
Advice don't install won"t work even what the develloper said, seach for a other PSP with betere payment plugins for Prestashop

**Comment by blikflits** [comment]
Hello,

I use the theme Panda (sunnytoo.com) with One page Supercheckout from
Knowband.

Regards,
Jan

Op do 29 okt. 2020 om 10:49 schreef SimonasB88 <notifications@github.com>:

**Comment by SimonasB88** [comment]
Hey @blikflits 
Thanks for contacting our team !

In order to investigate your issue and help you efficiently, can you send us an access to your backoffice with its url and a FTP access to your store:
URL back office:
login back office:
password back office:

FTP host:
FTP login:
FTP password:
FTP port:

Do this to support@invertus.eu.
Thank you.

Best Regards.

**Comment by SimonasB88** [comment]
Hey all,

We have found issue with Supercheckout module regarding this Mollie compatibility case:

There is code in _modules/supercheckout/views/js/front/supercheckout.js_ that adds .alert-info class to closest to payment_method <li> element.

`$('input[name="payment_method"]:checked').closest('li').addClass('alert-info');`

There is css in it that shows all radio buttons checked by _.alert-info modules/supercheckout/views/css/front/style.css_

```
.custom-radio.alert-info label:after {
    opacity: 1;
    -webkit-transform: scale(1);
    transform: scale(1);
}
```

Supercheckout module has it so all Mollie payments would be in one <li> element that is why everything is displayed as chosen.

It’s best to support Supercheckout module support to fix this issue, because there is a lot of logic and it may break if we change something. If you still decide for us to fix it, the shop should be downloaded with a database to test it fully.

That would take some effort, because we are not covering the Supercheckout module development. Probably this issue could be repetitive for any other payment modules. We advise you to contact Supercheckout module creators and you can provide the information we have checked.

Best regards!
