### ISSUE TITLE
MYSQL Error on Order tab in BO when activating module

### ISSUE THREAD

**Issue by BenSJAS** [mollie/PrestaShop#237]
### Actual behavior

When module is activated, it throws the following error on the Order tab in my Prestashop 1.7.6.8 backoffice :

`Mauvaise requête SQL
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'mol.`transaction_id`, shop.name as shop_name FROM `ps_orders` a LEFT JOIN ' at line 10`

### Environment
* PrestaShop version: 1.7.6.8 
* Mollie module version: 4.0.9 
* PHP version: 7.3
* MySQL 5.7

![Capture d’écran 2020-11-09 à 12 50 44](https://user-images.githubusercontent.com/74183241/98537908-439b1400-228a-11eb-8d0e-846b755478b9.png)

**Comment by BenSJAS** [comment]
@SimonasB88 Please help, we'd like to go live ASAP !

**Comment by SimonasB88** [comment]
Hello @BenSJAS thanks for your message,
Did you make an upgrade from 3.5 version to 4.0.9?
First, did you reset the module after upgrade?

Best Regards.

**Comment by BenSJAS** [comment]
Hi @SimonasB88  !
Thanks for your answer.
This is a fresh install, we just downloaded the module for the first time.

**Comment by SimonasB88** [comment]
Hey @BenSJAS hm this is kinda odd,

In order to investigate your issue and help you efficiently, can you send us an access to your backoffice with its url and a FTP access to your store:

URL back office:
login back office:
password back office:


FTP host:
FTP login:
FTP password:
FTP port:

And send everything to support@invertus.eu. I will check with the development team.

Best regards.

**Comment by BenSJAS** [comment]
Cool thanks !
Will do now.
Best regards
