### ISSUE TITLE
Pay by credit card sends Awaiting bank wire payment

### ISSUE THREAD

**Issue by wilva** [mollie/PrestaShop#265]
### Expected behavior
Do not send "Awaiting Bank Wire payment" emails

### Actual behavior
Paying online via credit card (or another non wire option) sends a "YOU HAVE SELECTED TO PAY BY WIRE TRANSFER. " email.

### Steps to reproduce the behavior
The "Bank Transfer" option is disabled (I don't want to support that even)
Under Advanced "Send mails when awaiting" is set to "NO"
Buying a product and selecting credit card then triggers the above email. Very confusing for an enduser.

### Environment
* PrestaShop version: 1.7.7.0 
* Mollie module version: 4.1.3
* PHP version: 7.2.34

**Comment by Saimis777** [comment]
Hello @wilva and thank you for your message!

We've tried to replicate your described issue in our local test environment, followed your given steps, but couldn't encounter the same email, error, I'm adding screenshots of what we've done, and what we've encountered:

Did an order on the test page via bank card:
![image](https://user-images.githubusercontent.com/75423142/102638523-4aa62380-4160-11eb-8c60-7a1e6006ddd3.png)

Then received a confirmation, and payment accepted emails:
![image](https://user-images.githubusercontent.com/75423142/102638606-73c6b400-4160-11eb-912e-db13e3dee81b.png)

In the orders section the order is confirmed:
![image](https://user-images.githubusercontent.com/75423142/102638696-9789fa00-4160-11eb-80ec-12cf4d3a36b5.png)

And here are the email logs for this order, proving that no "awaiting" emails were sent:
![image](https://user-images.githubusercontent.com/75423142/102638833-cdc77980-4160-11eb-9331-d51d3f728e28.png)


Maybe you would be able to include screenshots or a video of what exact steps need to be taken in order to reproduce this issue? We would greatly appreciate that! And it would be easier to identify why and how are you encountering this!

Will be looking forward to your reply!

Best regards,
Invertus Support team

**Comment by wilva** [comment]
Hi,

Thanks for testing.

This was my test:
![image](https://user-images.githubusercontent.com/43706927/102641865-1715ca00-415d-11eb-8b4a-8aee3733e85a.png)

and the emails send then look like this:
![image](https://user-images.githubusercontent.com/43706927/102642018-547a5780-415d-11eb-9bc8-7a48cc262789.png)

As you can see that doesn't match up.

I'm considering wiping the configuration and install the mollie integration fresh to see if that fixes the issue.
This is not a very active shop (first rolling the update out on an inactive shop) and I upgraded from the 4.0.3 (or perhaps 4.0.9)

I can wait a bit if there is something else you want me to verify.

**Comment by Saimis777** [comment]
Thanks for that, I see.

So firstly, could we make sure that you have the latest, updated version of module? You can download the latest one here -https://github.com/mollie/Prestashop/releases

So what you can firstly do if this is not a too important installation, you can delete the old one, install the latest one from my given link, and see if the issue persists!

And let me know with the outcome!

Best regards,
Invertus Support team

**Comment by wilva** [comment]
Hi,

I'm sure it is 4.1.3 as that is what I just installed.
![image](https://user-images.githubusercontent.com/43706927/102645981-9c03e200-4163-11eb-868e-8db3fd188142.png)

There is no doubt about that part.
I will delete the install once I get a chance. Maybe later today, otherwise early next week.

**Comment by wilva** [comment]
OK.. had a few minutes to try it out.
Did a complete uninstall.. removing folder.
Then a fresh install, used defaults.
Added the live key, enabled the payment options I want to support and now it works OK.
So you can close this issue.

Although I still think it is weird that an update has this kind of side effect..

**Comment by Saimis777** [comment]
If you will have any further questions, or need any help, please let us know!

Closing the issue for now.

--
Best regards,
Invertus Support team
