### ISSUE TITLE
The "Overboeking" method triggers Prestashop's Bank Transfer module

### ISSUE THREAD

**Issue by toretto** [mollie/Prestashop#27]
Hey all,

I just got a report from a client regarding the "Overboeking" option. Apparently, this option will trigger the "Bank Transfer" module. There's two possible scenarios:

* If the Bank Transfer module has, at some point, been configured, it'll then send a mail urging to send the payment to the old bank account. Additionally, they'll be told to transfer the money to the Mollie account (which is the way it should be)

* If it wasn't configured, it'll still send the mail from the Bank Transfer module, but with empty values for the address / bank number.

Ideally, no mails should be sent by the Bank Transfer module. After all, it's not active and this is being handled by Mollie when visiting the Payment page. As it stands now, using the "Overboeking" option built into Mollie isn't feasable and we'll need to re-enable the old Bank Transfer module.

**Comment by Trendweb** [comment]
Hi @toretto ,

Do you still need support on this issue?

Regards

**Comment by Trendweb** [comment]
Hi @toretto  ,

We are closing this issue because there hasn't been any response. You can still place comments to let us know if you still need support. You can also contact us at info@trendweb.nl for further support, because we really would like to solve the problem at hand. We will close comments on this issue after 1 week.

Regards
