### ISSUE TITLE
Some checkout paiements not diplayed

### ISSUE THREAD

**Issue by davidsmoker** [mollie/PrestaShop#275]
### Expected behavior
after install
Bancontact & ideal and appel pay not display in front office

### Steps to reproduce the behavior
install new verion

### Environment
* PrestaShop version: 1.7.6.8 
* Mollie module version: 4.1.3 
* PHP version: 7.2.34

**Comment by Saimis777** [comment]
Hello @davidsmoker,

Thank you for your message. Could you clarify if you've enabled those payment methods for all countries? Do they have any restrictions in the back office? Also, I would highly suggest installing the latest Mollie version which was released yesterday - 4.2.0, you can download it here - https://github.com/mollie/Prestashop/releases

Looking forward to your reply!

Best regards,
Invertus Support team

**Comment by davidsmoker** [comment]
hello,

I had version 4.1.3, last night I updated it to 4.2.0

after update payment options Bancontact, ideal and appel pay were no longer available in the front office

I have the same settings as the previous version

I have reinstalled the previous version again

**Comment by Saimis777** [comment]
@davidsmoker Did you try resetting the module and re-entering the settings, and then try to checkout? And made sure that after resetting that the payment methods are enabled in mollie.com dashboard? As we did not find a similar issue as mentioned.

Looking forward to your reply!

Best regards,
Invertus Support team

**Comment by pantoffelke** [comment]
I had the same problem and was using restrictions in the mollie module for some countries.
When select all countries then it work again.

**Comment by davidsmoker** [comment]
Thanks pantoffelke ;-) (twerkt lol)

But apple pay still not working  :-(

**Comment by Saimis777** [comment]
@davidsmoker Would you be able to provide your front office / back office + FTP details to support@invertus.eu? We could then check the issue further, and investigate on why Apple pay is not working in your shop.

Looking forward to your reply!

Best regards,
Invertus Support team

**Comment by d3monnn** [comment]
I have the same issue, upgraden to 4.2.0 this morning. reinstalled the module but the country restrictions do not seem to work.

iDeal only for "the netherlands" does not show up for a NL address, yet if selected for all countries it shows up everywhere.
Apple Pay does not show up in the options (enabled in Mollie) with or without the country restrictions.

**Comment by Saimis777** [comment]
@d3monnn Thank you for your message, we're currently investigating the issue, I will keep you updated once I receive an update from the development team!

Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hello @davidsmoker @d3monnn, the changes were made, and a pull request has been submitted for the fix, once it gets approved, I will notify you, and send the link with the merged fix.

Also, answering @davidsmoker question about order confirmation emails:

So order confirmation email is sent by Prestashop core when the order is being validated.  To avoid sending order confirmation we implemented the setting in mollie in “ADVANCED SETTINGS” tabs there is a “Send order confirmation email” setting:

![image](https://user-images.githubusercontent.com/75423142/105016824-c939fd80-5a4b-11eb-8749-63d40798c76d.png)

Where you can select when to send an order confirmation email. So you can set to send order confirmation emails when the order is Paid only.

Best regards,
Invertus Support team

**Comment by davidsmoker** [comment]
Hello,

thank you for the information

In my front office I like to have bancontact on top, but when you change a setting in the mollie module it is always placed at the bottom.
You then have to put it back in the right place.

Concerning the logo of credit cards, we can change it, but when you upload a new one, it does not take it.

David

**Comment by Saimis777** [comment]
@davidsmoker,

Could you maybe clarify your concern a bit? You want bancontact to appear as the first option? Maybe you could share a screenshot to get a better understanding of what you have in mind?

Looking forward to your reply!

Best regards,
Invertus Support team

**Comment by davidsmoker** [comment]
sorry dutch speaking guy ;-)
when you change somthing in module, bancontact go under paypal
https://prnt.sc/x80jki

must have put back to the top

**Comment by davidsmoker** [comment]
If I am not mistaken, you can also change the name?
https://prnt.sc/x80rdl

FO: 
https://prnt.sc/x80vh4

**Comment by Saimis777** [comment]
Thanks for the additional information, will check it with the team, and get back to you!

Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hello @davidsmoker,

I've clarified this with the team, the alignment of Bancontact should be displayed the same way as it is done in the admin area, that way they will be shown when the order is being processed, as for the name change, yes it's left there for the user to change it for himself.

Best regards,
Invertus Support team

**Comment by Ditwo** [comment]
_Some checkout paiements not diplayed_

I had the same problem using restrictions in the mollie module for some countries, or even if all countries are checked,
Prestashop 1.7.6.5
Mollie 4.2.0

When  I investigate into the mollie module,  I can see in mollie.php hookpaymentOptions() doesn't return the methods.  **To sum up, it's due to the mol_country table that is empty. If I insert a line like creditcard / id_country, the payments options are displayed**.

Here is the process (Desc sorted).
[6]   ...modules/mollie/src/Repository/ MethodCountryRepository.php   checkIfMethodIsAvailableInCountry() :  table mol_country. is empty,  method not taken into account
[5]   ...modules/mollie/src/Service/PaymentMethod\PaymentMethodRestrictionValidation   EnvironmentVersionSpecificPaymentMethodRestrictionValidator.php isValid()   > isCountryAvailable() > checkIfMethodIsAvailableInCountry()
[4]   ...modules/mollie/src/Service/PaymentMethodService/PaymentMethodRestrictionValidation.php  isPaymentMethodValid()   $paymentRestrictionValidator->isValid($paymentMethod)    (creditcard, bancontact…)
[3].../modules/mollie/src/Service/PaymentMethodService/PaymentMethodRestrictionValidation.php  isPaymentMethodValid()   $paymentRestrictionValidator->isValid($paymentMethod)
[2]   .../modules/mollie/src/Service/PaymentMethodService.php    this->paymentMethodRestrictionValidation->isPaymentMethodValid
[1]   .../modules/mollie/mollie.php hookpaymentOptions() >   getMethodsForCheckout() $paymentMethod = $paymentMethodRepository(…)

Hope it is useful.
Regards,
Denis

**Comment by Saimis777** [comment]
Hello @Ditwo and thank you for that!

We are going to include this fix in the 4.2.1 release! Your feedback is greatly appreciated!

Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hello, the new version of Mollie - 4.2.1 was just released!

Please find the link for the download here - https://github.com/mollie/Prestashop/releases

And let us know with any feedback regarding the new version!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hello again,

Due to the issue being solved in the 4.2.1. release, I will close it for now, if you will still encounter any issues regarding this or any other topic, let us know!

--
Best regards,
Invertus Support team

**Comment by davidsmoker** [comment]
no :-(

still have problems with apple pay

**Comment by Saimis777** [comment]
@davidsmoker Even after installing 4.2.1 version, clearing cache, and making sure that no locale is limited for Apple pay?

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
@davidsmoker 

Could you also maybe share feedback of how you encounter the issue now?

Looking forward to your reply!

--
Best regards,
Invertus Support team

**Comment by davidsmoker** [comment]
hi,

https://prnt.sc/xt83tq

https://prnt.sc/xt890i

is still not shown in FO

**Comment by Saimis777** [comment]
Thank you for that!

Checking further.

--
Best regards,
Invertus Support team

**Comment by petrovv77** [comment]
> hi,
> 
> https://prnt.sc/xt83tq
> 
> https://prnt.sc/xt890i
> 
> is still not shown in FO

I don't know what device you are testing with. But Apple Pay is only shown if it is supported on the device

**Comment by MariannevdS** [comment]
Same issue here with the mollie 4.2.1. version no apple pay in FO (and not visible on iphone)

**Comment by davidsmoker** [comment]
Hi 

test yesterday on iphone ( with apple pay activated) 

Not working :-(

**Comment by MariannevdS** [comment]
And one more issue we have is missing name and email in the header of the new_order email (to the webshop) executed by the mail-alert module.
Looks similar as the missing products. the template is unchanged, the values {firstname}{lastname} and {email} are not processed in the mail. 
Showing only the brackets :Een nieuwe bestelling op de Eenhoorn Koffie en Thee door: ()
![Schermafbeelding 2021-01-30 om 09 53 39](https://user-images.githubusercontent.com/78209224/106352255-bcd26200-62e1-11eb-98c4-8d33f7f7ae13.jpg)

**Comment by davidsmoker** [comment]
the same problem 

do you have a multistore?

**Comment by MariannevdS** [comment]
Yes

**Comment by MariannevdS** [comment]
Is there a solution or should i roll-back to previous version of the module?

**Comment by davidsmoker** [comment]
Noppes :-(

mollie module not optimized for multistore

**Comment by MariannevdS** [comment]
Does an older module still work with 1.7.7.1 ?

**Comment by Maz-Invertus** [comment]
Hi everyone!

Sorry to hear that there is issue with Multistore. Our support team will pick it up and make the initial investigation next week.
Multistore logic is very complex for the module compatibility so it might be not so quick change, but we'll to our best to find a quick fix.

In order to rollback the module you'd need to reset the module and if the rollback is to lower than v4, you would need to delete Mollie database tables.

Thank you for being active community members!

--
Best regards,
Invertus Support team

**Comment by MariannevdS** [comment]
Hi,
I don't know if it is only multistore, i see one person having the same problem but it is with the 4.2.0 version. We only use mollie in one store does that help? It all worked really well before.

**Comment by Saimis777** [comment]
@MariannevdS 

We're currently investigating this further, I will let you know with the progress!

Also, which version was working before really well could you clarify? To roll back the version, you would need to delete the module from the files + the database, and re-install the previous one needed.

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hello everyone thank you for your patience,

We've re-investigated the issue, tested it, and made sure that apple pay is now displayed and working correctly as it should, we've added this fix to the 4.2.2 release, which we are planning to release next week (if nothing goes wrong).

The latest version will be uploaded here - https://github.com/mollie/Prestashop/releases

Be sure to follow that link for the latest update, and let me know if you will have any further questions!

I will close this issue for now, if it will re-appear after the release, let me know, though we've tested it several times, and it should definitely work now.

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hello everyone, hope you're having a nice day so far!

We've just launched the 4.2.2 Mollie version, maybe you could try and install it, and provide any feedback regarding the new version?

You can download the latest version here - https://github.com/mollie/Prestashop/releases

We debugged the Apple Pay payment method displaying, developer implemented the cookie fix, and the fix was implemented in the 4.2.2 release.

Looking forward to your feedback!

--
Best regards,
Invertus Support team
