### ISSUE TITLE
Text not showing up

### ISSUE THREAD

**Issue by joskepeeters** [mollie/Prestashop#35]
At my checkout page for mollie the text for 'Bancontact Mister Cash' and 'KBC' is not showing.
Only the images of those payment methods are visible.

Anyone got an idea how to fix this?
![text](https://cloud.githubusercontent.com/assets/25354419/23590025/e90fb11a-01d8-11e7-83b7-bb8fd8ea235c.JPG)

**Comment by Trendweb** [comment]
Hi @joskepeeters ,

Have you managed to solve this problem? If not, please let us know so we can offer you support on this problem.

**Comment by joskepeeters** [comment]
Hi 
No the text is still not showing up. I installed the module again but without succes. 
I cant find the source code to change it.

**Comment by Trendweb** [comment]
Which Prestashop version are you currently using? Can you please provide me with a link and could you enable the debug mode so i can investigate the problem? I fully understand if you don't want to disclose your test shop. So you can also send an e-mail to info@trendweb.nl so we can work from there and post the solution here.

**Comment by Trendweb** [comment]
Hello @joskepeeters ,

Could you please let us know if you still need support? Otherwise, we have to close the issue.

Regards

**Comment by joskepeeters** [comment]
Hi 
I've had very busy week. 
I still need support on this but i dont have a test shop online. Only my live webshop www.bellesperles.be

**Comment by Trendweb** [comment]
Hi @joskepeeters ,

Your domain www.bellesperles.be has been suspendended by your hosting provider.

**Comment by Trendweb** [comment]
Hi @joskepeeters ,

Could you please provide us with the following information:

- server information and your prestashop version (Choose: advanced settings >> information);
- the version number of the Mollie Module you are currently using (Choose: Modules >> Modules & Services).

Regards

**Comment by joskepeeters** [comment]
Serverinformatie: Linux #1 SMP Tue Jul 12 18:30:56 UTC 2016 x86_64
Server softwareversie: Apache/2
PHP-versie: 5.6.25
Geheugenlimiet: 256M
Maximale uitvoeringstijd: 120
Maximale bestandsgrootte voor uploads: 64M

PrestaShop-versie: 1.7.0.4

Mollie Payment Module v1.3.0



2017-06-19 10:14 GMT+02:00 Trendweb <notifications@github.com>:

**Comment by Trendweb** [comment]
Hi @joskepeeters ,

Could you please try the latest version of the Mollie Payment Module which you will find enclosed in this comment? This one is compatible with Prestashop 1.7+ (up to version 1.7.1.2).

[mollie.zip](https://github.com/mollie/Prestashop/files/1084632/mollie.zip)

We are currently working on a new Mollie Payment Module which will be placed on Github as soon as possible.

We also strongly recommend you to upgrade to the latest version of Prestashop (1.7.1.2). A lot of bugs and security issues have been solved since version 1.7.0.4.

Before upgrading your live webshop to the latest version, create a full backup of your store. Then, create a test version of your webshop and update this one first to prevent any errors / problems.

Always make sure (before upgrading) that all of your modules are compatible with 1.7.1.2. as well. And of course, you can ask your webdesigner to do this for you.

Please let us know if this solved your problem.

Regards

**Comment by joskepeeters** [comment]
Thx for your help.
I will try this next week.


2017-06-19 13:04 GMT+02:00 Trendweb <notifications@github.com>:

**Comment by Trendweb** [comment]
Hi @joskepeeters ,

Have you had a chance to try our suggestions? Please let us know so we can solve this problem.

Regards

**Comment by Trendweb** [comment]
Hi @joskepeeters ,

Could you please let us know if you still want support on this issue?

Regards

**Comment by Trendweb** [comment]
Hi @joskepeeters ,

We are closing this issue because there hasn't been any response. You can still place comments to let us know if you still need support. You can also contact us at info@trendweb.nl for further support, because we really would like to solve the problem at hand. We will close comments on this issue after 1 week.

Regards
