### ISSUE TITLE
Illegal mix of collations (utf8_general_ci,IMPLICIT) and (utf8_unicode_ci,IMPLICIT) for operation '='

### ISSUE THREAD

**Issue by MonkeyTime** [mollie/PrestaShop#351]
### Expected behavior

Orders list in back-office displayed

### Actual behavior

Mauvaise requête SQL
Illegal mix of collations (utf8_general_ci,IMPLICIT) and (utf8_unicode_ci,IMPLICIT) for operation '='

back-office -> orders: list not displayed

### Steps to reproduce the behavior

under prestashop 1.7.6.3 with lot of orders, just install mollie module 4.2.4 update to mollie 4.3.0 module and visite back-office -> orders list

### Environment
* PrestaShop version: 1.7.6.3
* Mollie module version: 4.3.0
* PHP version: 7.2.X
* MySQL 8.0.22

**Comment by Saimis777** [comment]
Hello @MonkeyTime !

Thank you for your message, we will try to replicate the issue, and I will get back to you if further clarifications will be needed!

Have a nice day until then!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hey again @MonkeyTime ,

Could you also provide your BO+FTP credentials to the following email - support@invertus.eu? We have an idea what could the issue be and might just install the fix to your shop directly.

Just be sure not to reply to this message, but send a separate email so it would not get shared to Github.

Looking forward to your reply!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hi @MonkeyTime ,

The issue is that our tables in the database are with utf8_general_ci and your Prestashop tables are with utf8_unicode_ci. An "illegal mix of collations" occurs when an expression compares two strings of different collations.
Here is information on how the collation of the database can be changed - https://stackoverflow.com/questions/1294117/how-to-change-collation-of-database-table-column

And here's a module with a changed table collation after reinstalling the module the error should be gone.

The updated module - https://ufile.io/q33t0xxk

Let me know if everything works for you!

--
Best regards,
Invertus Support team

**Comment by MonkeyTime** [comment]
Hi @Saimis777 ,

Tested completly uninstall from catalog module -> install via module manager -> install a module (zip) -> activate but no change, already the same problem.

**Comment by Saimis777** [comment]
Hi @MonkeyTime ,

As I understand the temporary changes helped, and they work, is that correct?

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hi @MonkeyTime ,

Do you need any further assistance?

Looking forward to your reply!

--
Best regards,
Invertus Support team

**Comment by SimonasB88** [comment]
Hello,
This issue is being closed now for the inactivity for some time. Please raise a separate ticket in Mollie Issues if the issue still occurs.
Thank you for understanding!
Have a great day.

Best Regards,
Invertus Support Team
