### ISSUE TITLE
Cannot install mollie module keeps saying fatal error - prestashop 1.6.1.10

### ISSUE THREAD

**Issue by charlypj** [mollie/Prestashop#37]
I've tried to install the mollie module in several ways now (upload ftp, upload at prestashop), but it keeps giving a blank screen and this error when I want to install or configure the module which is not enabling me to proceed with the module. If anyone knows the solution thank you!

Charlotte

Error message:
[PrestaShop] Fatal error in module file :/home/kalimb5/public_html/modules/mollie/mollie.php:
Uncaught exception 'Exception' with message 'String could not be parsed as XML' in /home/kalimb5/public_html/modules/mollie/mollie.php:734 Stack trace: #0 /home/kalimb5/public_html/modules/mollie/mollie.php(734): SimpleXMLElement->__construct('') #1 /home/kalimb5/public_html/modules/mollie/mollie.php(411): Mollie->_getUpdateMessage('https://github....') #2 /home/kalimb5/public_html/controllers/admin/AdminModulesController.php(867): Mollie->getContent() #3 /home/kalimb5/public_html/controllers/admin/AdminModulesController.php(1116): AdminModulesControllerCore->postProcessCallback() #4 /home/kalimb5/public_html/classes/controller/Controller.php(178): AdminModulesControllerCore->postProcess() #5 /home/kalimb5/public_html/classes/Dispatcher.php(367): ControllerCore->run() #6 /home/kalimb5/public_html/admin123/index.php(58): DispatcherCore->dispatch() #7 {main} thrown

**Comment by Trendweb** [comment]
Just to be sure before proceeding: did you install the .zip file you downloaded from https://github.com/mollie/Prestashop (Prestashop-master.zip) or did you install (the right one) you got from https://github.com/mollie/Prestashop/releases (mollie.zip).

First: download mollie.zip from https://github.com/mollie/Prestashop/releases
Second: open the folder modules in your public_html through your ftp and remove the folder named 'mollie'
Third: Install mollie .zip in the backoffice and activate it. It should be flawless. Please let us know if this solved your problem.

Kind regards

**Comment by charlypj** [comment]
Hi! Thank you for your reply. I downloaded the file from
https://github.com/mollie/Prestashop/releases.
I removed and have tried to install it in the backoffice several times now,
but it keeps giving the same fatal error... :(

Regards Charlotte

2017-05-16 17:21 GMT+02:00 Trendweb <notifications@github.com>:

**Comment by Trendweb** [comment]
Hey Charlotte,

it might be your PHP settings which cause the error. Upon install, it checks if there is an update available. Does your hosting provider allow you to change the PHP settings? if so, please set allow_url_fopen to "on" and try it again. Otherwise, please contact your hosting provider to change this setting.

Maybe a bit of a "workaround" to at least get it installed:

Unzip mollie.php and open mollie.php in the unpacked folder. On line 415 you will see $update_message = $this->_getUpdateMessage('https://github.com/mollie/Prestashop');

for the time being, outcomment it like so:

//$update_message = $this->_getUpdateMessage('https://github.com/mollie/Prestashop'); (just put 2 slashes in front of it...)

This way it will skip checking for an update for the time being untill your hosting provider changed the PHP setting.

Save the file mollie.php and create a new .zip folder named "test". Now move and place the normal folder named "mollie" inside the .zip and try to install it.

After the PHP settings have changed, please install the "normal" mollie.zip so it can check for updates again.

You can also contact me at info@trendweb.nl for this issue, and we will get it solved.

Kind Regards,

Martijn

**Comment by Trendweb** [comment]
To save you some time and trouble, i have attached a different version. Just download it and install it. I have outcommented $update_message = $this->_getUpdateMessage('https://github.com/mollie/Prestashop'); for you.

Regards
[test.zip](https://github.com/mollie/Prestashop/files/1005273/test.zip)

**Comment by charlypj** [comment]
Thank you so much Martijn!
I am gonna try to install your version in the morning.

Regards,
Charlotte

**Comment by Trendweb** [comment]
You're welcome! Let us know if it worked for you :)

**Comment by charlypj** [comment]
Hi Martijn, I installed the test file on my site and it seems to all be
working fine! No error messages anymore.
Thank you again for your help.
Regards,
Charlotte

2017-05-17 10:14 GMT+02:00 Trendweb <notifications@github.com>:
