### ISSUE TITLE
mollie.js load on every page

### ISSUE THREAD

**Issue by petrovv77** [mollie/PrestaShop#370]
js.mollie.com/v1/mollie.js load on each page and use only 108.4 KiB out of 208.8 KiB. Lots of unused JavaScript on the non checkout pages.
I understand that this is necessary to create cookies in advance for the needs of applepay etc? But is it possible to load the script only at the shopping cart and further pages?

### Environment
* PrestaShop version: 1.7.7.5
* Mollie module version: 4.3.0 
* PHP version: 7.2.24

**Comment by Saimis777** [comment]
Hey @petrovv77 ,

Thank you for the issue!

I will consult with the development team regarding the case, and will let you know!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hi again @petrovv77 ,

We used to add JS only on checkout but because we want to support checkout modules we removed the checker and add JS on every page. If we add it back then custom checkout pages wont work with Mollie because we don't know its controller name.

Please let me know if you have any more questions or if we can close the issue!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hi @petrovv77 ,

Due to inactivity, I will close this issue for now, if you'll have more questions or will need any assistance, feel free to re-open this issue, or raise a new one!

Have a nice day!

--
Best regards,
Invertus Support team
