### ISSUE TITLE
Plugin doesn't support ordernumber as description in version 1.3.0

### ISSUE THREAD

**Issue by robertmollie** [mollie/PrestaShop#39]
The issue results that the merchant can't find the customer back in his/her administration.

**Comment by Trendweb** [comment]
Hi @robertmollie ,

We are currently working on an update, so the module will be compatible with PS version 1.5 to 1.7. The ordernumber as description will be added in the update.

Regards

**Comment by robertmollie** [comment]
Hi @Trendweb,

Thank you for your quick response, our clients would appriciate the update!

Best regards!

**Comment by carolinecosmetics** [comment]
Great, thankx for developing a solution. When can I expect the update?
Working with Mollie / Banking is really diificult now and I have to double check each payment.

Best regards
Henk

**Comment by Trendweb** [comment]
Hi @carolinecosmetics  / Henk,

We are working very hard to solve a few other problems as well, so we can't provide you with a exact release date yet. After the module has been thoroughly tested, we will update the module immediately on Github. We do expect it to be done in about 1 week / 2 weeks at most. As soon as the module has been updated on Github, you will automatically recieve a notification on the Mollie Configuration Page in the Backend of your Prestashop Store.

If you'r experiencing any other problems with the Mollie Module, please let us know so we can solve these as well.

Regards

**Comment by carolinecosmetics** [comment]
Hi
Can you tell me when the solution is ready to update the module.

Kind regards
Caroline Cosmetics / Henk

**Comment by Trendweb** [comment]
Hi @carolinecosmetics ,

The module is currently being reviewed and tested. We are working very hard to get the module ready as soon as we possibly can. It will updated on Github after it has been thoroughly tested to prevent any problems.

Kind Regards

**Comment by carolinecosmetics** [comment]
Thankx for quick reply

**Comment by paintspec** [comment]
I got a notification to upgrad to 1.3.1, after downloading this version it seems it still is 1.3.0, nothing changes, even when i remove the old module and install the downloaded 1.3.1 version
https://www.screencast.com/t/fEo4eCdNk
https://www.screencast.com/t/MTqwmOK4rON

Does this means its still not ready?

**Comment by Trendweb** [comment]
HI @paintspec ,

Thank you for notifying us. We already reported this to Mollie, the version number in the file mollie.php has not been changed. This:
public $version                = '1.3.0';
should have been set to
public $version                = '1.3.1';

That's why you're getting a notification about an update, even though you have the right version installed. This will be solved as soon as possible. 

Kind regards

**Comment by Trendweb** [comment]
Hi @carolinecosmetics ,

It doesn't support that yet. I'm finishing up on the last problem to be solved. The latest beta version does send the order id and also the order reference to Mollie, however, when the order is validated as the payment is iniated, it sends an order confirmation to your client even if the order hasn't been paid yet.

This leads to confusing situations, because people will contact you if their order has been properly cancelled or not. 

The piece of code responsible for sending that particular e-mail is a part of the validateOrder function and there is no setting available to prevent this from being sent.

This also one of the main reasons why it was removed in the past:

https://github.com/mollie/Prestashop/releases?after=v1.0.8

(see comments from version 1.0.3 and up)

So i'm currently writing a "workaround" so the order will be properly validated when the payment is initiated (so the order id and the order reference will be sent to Mollie), without sending the order confirmation before the order has been paid.

I have added a working bèta version which can be use for Prestashop 1.6 (note that in this version, emails are still being sent when payment is initiated). After you have installed the module, you can change the description to this example: Cart % Ordernumber {order.id} Reference {order.ref}

After you have made a test payment, log in to your account at mollie.com and change the dashboard view to "test modus". as you can see, it sends the info you need to Mollie.

[mollie-prestashop-1.3.2_beta.zip](https://github.com/mollie/PrestaShop/files/1225792/mollie-prestashop-1.3.2_beta.zip)

As soon as the last problem is solved, i will upload a new PS 1.6 version into this issue, and of course, an update will be placed on Github.

Regards

**Comment by staeren** [comment]
something goes wrong when customer had done payment. it is like a double registration, see https://www.dropbox.com/s/g5qor0vob470a6o/Schermafdruk%202017-09-22%2008.13.18.png?dl=0

**Comment by Trendweb** [comment]
Hi @staeren ,

Is this happening with the temporary beta version we posted in this issue?

Regards

**Comment by firstred** [comment]
Does the Mollie module use multiple order states? If so, make sure that all subsequent states are added like in this example:
```php
$history = new OrderHistory();
$history->id_order = (int) $order->id;
$history->changeIdOrderState((int) Configuration::get(static::SHIPPED), (int) $order->id, !$order->hasInvoice());
$history->addWithemail(true);
```

The first state is probably added via `PaymentModule::validateOrder` and might not always have a "validating status" (since users are free to choose). Which means it can add the payment info, but not see the registered payment as something that belongs on the final invoice.
As a result, when adding the second state, it will check the amount on the invoice that is still due (that's all of it when using a non-validating status!) and will again register this as a payment, causing it to double the amount.
Now, adding that third parameter (`!$order->hasInvoice()`), basically forces PS to check if there already is an invoice before adding the payment. If it is, it will link the previous amount with the just generated invoice and everything should be fine from now on. I hope you are still following.

**Comment by staeren** [comment]
hello,

the first state added via PaymentModule Mollie has no “validated” state, it is set as “paid”, invoice is not yet created. this invoice is only created when order is shipped.

so what do you suggest to solve this problem?

kind regards
dimitry

Op 22 sep. 2017, om 08:35 heeft Michael Dekker <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Does the Mollie module use multiple order states? If so, make sure that all subsequent states are added like in this example:

$history = new OrderHistory();
$history->id_order = (int) $order->id;
$history->changeIdOrderState((int) Configuration::get(static::SHIPPED), (int) $order->id, !$order->hasInvoice());
$history->addWithemail(true);

The first state is probably added via PaymentModule::validateOrder and might not always have a "validating status" (since users are free to choose). Which means it can add the payment info, but not see the registered payment as something that belongs on the final invoice.
As a result, when adding the second state, it will check the amount on the invoice that is still due (that's all of it when using a non-validating status!) and will again register this as a payment, causing it to double the amount.
Now, adding that third parameter (!$order->hasInvoice()), basically forces PS to check if there already is an invoice before adding the payment. If it is, it will link the previous amount with the just generated invoice and everything should be fine from now on. I hope you are still following.

**Comment by firstred** [comment]
I was thinking about changing the behavior of the Mollie module, but I am not sure if that is needed. Can you post the order history and configuration of the last payment status?

These ones:
![orderhist](https://user-images.githubusercontent.com/6775736/30732428-d3982b54-9f72-11e7-8d13-51c673f7619a.png)
![paymentstateconf](https://user-images.githubusercontent.com/6775736/30732427-d37e62f0-9f72-11e7-9d05-2b6cd49f3357.png)

**Comment by staeren** [comment]
see screenshots please:

https://www.dropbox.com/s/0ftqlxgzwjz7kdo/Schermafdruk%202017-09-22%2009.57.49.png?dl=0
https://www.dropbox.com/s/gy3k4iji4ioa1h5/Schermafdruk%202017-09-22%2009.58.15.png?dl=0
https://www.dropbox.com/s/jr65v4ihtsxraqj/Schermafdruk%202017-09-22%2009.58.50.png?dl=0

Op 22 sep. 2017, om 08:48 heeft Michael Dekker <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


I was thinking about changing the behavior of the Mollie module, but I am not sure if that is needed. Can you post the order history and configuration of the last payment status?

These ones:
[orderhist]<https://user-images.githubusercontent.com/6775736/30732428-d3982b54-9f72-11e7-8d13-51c673f7619a.png>
[paymentstateconf]<https://user-images.githubusercontent.com/6775736/30732427-d37e62f0-9f72-11e7-9d05-2b6cd49f3357.png>

**Comment by firstred** [comment]
Yup, that's exactly what I was afraid of. This configuration causes payments to be registered twice with most payment modules.

@Trendweb Are you following? This is undocumented (and unwanted) behavior in PrestaShop, but will be easy peasy to take care of once you know what's going on under the hood. It requires a few changes in the module, though.

**Comment by Trendweb** [comment]
Hi @firstred ,

We are currently developing 2 modules (1.5-1.6 and 1.7) which already have their own order statuses to prevent problems like this.

Regards

**Comment by firstred** [comment]
Hmmz, let me show you what I mean. Where can I find the latest 1.6 code? This repo?

**Comment by Trendweb** [comment]
@firstred ,

if you like to elaborate, please contact me at info@trendweb.nl

**Comment by firstred** [comment]
Sure thing!

**Comment by snowycatsoftware** [comment]
There is currently no proper method for sending the order id or order reference to Mollie when a customer places an order. This is because of the way Prestashop is buildt. If we do find a proper method to send the order id or order reference beforehand, it will be added to the Mollie module. Therefore we are closing this issue.

Kind Regards
