### ISSUE TITLE
Exception on hook paymentOptions for module. Curl error: Resolving timed out after 2000 milliseconds

### ISSUE THREAD

**Issue by kennethbruyninckx** [mollie/PrestaShop#405]
On September 10, 11 and 12th I received following error in Prestashop logs + had customers complain they could not pay for their order and their inability to pay co-incided with these errors:

Here is the error received on September 12th:

Error (3)  Exception on hook paymentOptions for module . [2021-09-12T20:04:59+0200] Curl error: Resolving timed out after 2000 milliseconds

After consulting on the Prestashop forum the suggestion was made that 2 seconds timeout is rather short.
Is there a reason why the timeout is set to 2 and not a higher value?

PS: before you tell me to upgrade to 4.3.3 I tried that around August 20th and was left with no payment options in my Prestashop, 
All settings seemed ok, payment options were active, the keys were correct, Prestashop and browser cache was cleared several times but still nothing, so after a couple of hours I went back to 4.3.1 on my live shop and payments options were available again and my customers could pay again.

### Environment
* PrestaShop version: 1.7.7.5
* Mollie module version: 4.3.1
* PHP version: 7.3

**Comment by Saimis777** [comment]
Hi @kennethbruyninckx ,

Thank you for your message!

There are no timeouts set for Mollie module, also we did not encounter any similar issues before, maybe you could send your BO + FTP credentials to - support@invertus.eu for further investigation?

Thank you!

--
Best regards,
Invertus Support team

**Comment by kennethbruyninckx** [comment]
Hi,

I'll send the requested details later today/tomorrow to the e-mail address requested.
You say the module has no timeouts defined?

Please have a look at \modules\mollie\vendor\mollie\mollie-api-php\src\HttpAdapter\CurlMollieHttpAdapter.php
on line 16 (version 4.3.1) you have the following code:

    /**
     * Default connect timeout (in seconds).
     */
    const DEFAULT_CONNECT_TIMEOUT = 2;

which is then later used in the function send on line 41.

**Comment by Saimis777** [comment]
Hi @kennethbruyninckx ,

Correct, this could be increased manually for now, we've already asked Mollie developers to update this part so it wouldn't cause any issues.

--
Best regards,
Invertus Support team

**Comment by PcmanNL** [comment]
Hello, I'm experiencing the same issue with the exception error.
Increasing DEFAULT_CONNECT_TIMEOUT did solve slow performance, but the Mollie payments are not being shown on the checkout. 
I'm using version 4.4.0

**Comment by Saimis777** [comment]
Hey @PcmanNL ,

Thanks for the information, the team is already informed. I will inform you once I will have further information on this!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hey @PcmanNL ,

Glad that it solved the issue, regarding the payments not being shown, did you try following these steps - https://github.com/mollie/PrestaShop/wiki/Troubleshooting#payment-method-does-not-appear-in-front-office ? 

--
Best regards,
Invertus Support team

**Comment by kennethbruyninckx** [comment]
@PcmanNL which value did you change it to?

**Comment by PcmanNL** [comment]
Thank you, it has been solved. Everything works again.

**Comment by Saimis777** [comment]
Hey @PcmanNL ,

Maybe you could share to which value you've changed it to, so it could stay in the history of this GitHub?

Looking forward to your reply!

--
Best regards,
Invertus Support team

**Comment by PcmanNL** [comment]
@kennethbruyninckx 
@Saimis777 
I have changed the value of DEFAULT_CONNECT_TIMEOUT to 10 seconds and since then no exceptions have been thrown anymore. 

When I'm on the checkout page and I click continue, it sometimes takes between 300ms to 10 seconds to load the step with payments options which are iDEAL and Bancontact
The load time of the shipping address form also varies from 100ms to a couple of seconds. 
I have cache and debug mode disabled and disabled all installed modules that do not belong to the Prestashop core. 
I don't exactly know how to test the performance and I also don't know what part of the code might be slow, so I hope the developers could look at it, we didn't had this problem before. 
If it is helpful our server hardware is E3-1220 v5 3GHz with 16 GB ddr4 memory and 2x 250 GB SAS 12Gbps disk in raid 1 and 200Mbps wan speed and 11ms ping.

**Comment by Saimis777** [comment]
Hi @PcmanNL ,

Thank you for sharing the details!

We will check the loading times, which PS/PHP version you are using?

As I understand this issue was not relevant before 4.4.0 release?

Looking forward to your reply!

--
Best regards,
Invertus Support team

**Comment by PcmanNL** [comment]
We are using Prestashop 1.7.6.9 and php 7.2.34 FPM and Apache/2.4.41
I have removed 4.4.0 and installed mollie module version 4.2.2 that I had from a backup in february 2021. 
4.2.2 version is a lot faster than 4.4.0 load times are: 

- 1st time 261ms, 
- 2nd time 203ms, 
- 3rd time 201 ms. 

I think something was changed between 4.2.2 and 4.4.0 that reduces the performance of the module. 

I hope you can fix it.

**Comment by Saimis777** [comment]
Hey @PcmanNL ,

Thanks for the detailed information, it is appreciated. 

I will check with the team on what was done, why did it slow down like that. 

And I will get back to you asap!

--
Best regards,
Invertus Support team

**Comment by AmandaMollie** [comment]
@PcmanNL - I'm closing this issue and we'll continue investigating via this issue -- https://github.com/mollie/PrestaShop/issues/408 

Thanks for all the detailed feedback!

**Comment by loonas** [comment]
Hi @PcmanNL @kennethbruyninckx ,

I hope that you are doing well!
I wanted to inform you that this issue has been fixed with our latest 5.0.0-beta2 version. You can find it and check it out [here](https://github.com/mollie/PrestaShop1.7/releases/tag/v5.0.0-beta2). 

Let us know if you have any questions or feedback!

Best regards,
Invertus Support team
