### ISSUE TITLE
Notice: Undefined index: Bancontact in /public_html/modules/mollie/mollie.php on line 933

### ISSUE THREAD

**Issue by vxmretail** [mollie/PrestaShop#41]
Hi All,

If I turn on the Debug function, I get 2 error messages at the checkout on step 5

Notice: Undefined index: Bancontact in /home/***/public_html/modules/mollie/mollie.php on line 933

Notice: Undefined index: KBC/CBC Payment Button in /home/***/public_html/modules/mollie/mollie.php on line 933

I have viewed the page and I do not see a name with the payment option. 'cta_text' => $ this-> long [$ method-> description]

![screenhunter_221 sep 08 19 19](https://user-images.githubusercontent.com/31775464/30223328-ada2879e-94ca-11e7-8571-3f6e0d19efba.jpg)

How can I add both descriptions to the module?
Thank you in advance.

**Comment by Trendweb** [comment]
Hi @vxmretail ,

We are Mollie's Prestashop partner and we also provide support for Mollie's customers who are experiencing problems with the Prestashop Module. Could you please contact us at info@trendweb.nl so we can provide you with a sollution?

Regards

**Comment by Trendweb** [comment]
By the way, which version of the Mollie module are you currently using?

because (i copied this from your post):

'cta_text' => $ this-> long [$ method-> description],

should be:

'cta_text' => $this->lang[$method->description],

If you upgrade to the latest version of the Mollie module (1.3.1) the problem should be solved.

Regards

**Comment by vxmretail** [comment]
Hi Trendweb,

I copied from the file mollie.php and i see 'cta_text' => $this->lang[$method->description], i type this wrong.

I have send you an email.
Regards
