### ISSUE TITLE
Same cart ID - order automatically cancelled after first payment expires

### ISSUE THREAD

**Issue by tajriba** [mollie/PrestaShop#424]
### Expected behavior
Do not cancel orders finally placed with other payment methods other then mollie.

### Actual behavior
See below

### Steps to reproduce the behavior
When you place an order with mollie (go to payment method) than go back. And pay with bankwire. The order is canceled later from mollie because transaction started. So the order is after all placed with normal bankwire payment method (not mollie) but get's the order state "canceled" from mollie!

### Environment
* PrestaShop version: 1.7.6
* Mollie module version: 4.4.1 
* PHP version: 7.2

**Comment by Saimis777** [comment]
Hi @tajriba ,

Thanks for the information,

We will try to replicate this issue from our end, and will let you know about further progress regarding this case.

Thank you for your patience.

--
Best regards,
Invertus Support team

**Comment by CooUoo** [comment]
Hello,

This issue even happens with Mollie only.
Yesterday, I had a similar case.
The client arrives on Mollie credit card payment page.
But he doesn't pay. He goes back (for whatever reason) to my site.
Few minutes later, he goes back again to checkout and goes again to Mollie credit card payment page, and he pays.
Payment accepted in Mollie and in PS BO > Orders. All fine.
But around 20mn later, the order got Cancelled in my PS BO > Orders.
I check Mollie board --> Paid. No problem here.
**BUT** I can see in Mollie board that the first access of the client to the payment page has its own previous EXPIRED record.
Both records in Mollie board (the PAID and the EXPIRED one) have the same cart ID in reference ! And this is where the mess up comes from.
I guess that the first access to the payment page got expired, without taking into account that the cart was paid later. So the order got cancelled because of the first access expiry.

@tajriba: I use your thread because I do believe this is the exact same issue. My apologies if you think I shouldn't have done that.

Regards

PS 1.7.7 - Mollie 4.4.1 - PHP 7.2

**Comment by Saimis777** [comment]
Thanks @CooUoo ,

For the detailed information!

I've forwarded the information to the team, and will let you know as soon as I'll have some answers!

--
Best regards,
Invertus Support team
