### ISSUE TITLE
not receiving an confirmation email.

### ISSUE THREAD

**Issue by Spiros333** [mollie/PrestaShop#444]
klarna orders getting cancel on there own

![image](https://user-images.githubusercontent.com/85503636/138128892-2ced9213-eaf6-4bc9-9fe2-0a802000d83c.png)
Environment
PrestaShop version: 1.7.6.2
Mollie module version: 4..4.1
PHP version: 7.2

**Comment by Saimis777** [comment]
Hi @Spiros333 ,

Thanks for your message.

Does all the Klarna payments after everything completed get cancelled in your shop? Or is it only for some of them? Also, could you provide screenshot from Mollie history?

Looking forward to your reply!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hey @Spiros333 ,

Maybe you could install the latest version of the module that was released just today? You can download it here -  https://github.com/mollie/PrestaShop/releases/tag/4.4.2

Because we've had an order cancellation issue, and it was resolved, and it's highly possible that it's related to this issue.

Looking forward to your reply!

--
Best regards,
Invertus Support team

**Comment by Spiros333** [comment]
Klarna status stays on Klarna payment authorized
It should change status in Klarna payment shipped.
![image](https://user-images.githubusercontent.com/85503636/139966677-dfad2ed9-3284-4eeb-b00b-e5b70c233dc5.png)

![image](https://user-images.githubusercontent.com/85503636/139966667-11c84073-c789-41c9-965d-4ae57eb56b22.png)

**Comment by Saimis777** [comment]
Hi @Spiros333 ,

Thank you for your message.

Can you confirm that everything is okay regarding the emails? If yes, can I rename the issue after the Klarna status issue?

--
Best regards,
Invertus Support team

**Comment by Spiros333** [comment]
yes we go from the one problem to the next
it seems everytime your team is fixing something another problem keeps existing.
Total not happy with the kind of support.

**Comment by Spiros333** [comment]
will it take months to have an good working plugin or not?

**Comment by Spiros333** [comment]
Im feeling like we are pilot or test users of your new release everytime.
Your try-outs is costing me customers with complains.

Is this the Invertus way of doing things?

**Comment by Saimis777** [comment]
Hi @Spiros333 ,

Thank you for your feedback.

We've investigated this with the Mollie team, seems that this might've been a 1 time issue, because even from the screenshot you've provided it is seen that the operation timed out, it might be due to a slow server, as we firstly send the webhook call.

Please let us know if you'll encounter this again so we could investigate deeper.

Thank you.

--
Best regards,
Invertus Support team

**Comment by loonas** [comment]
Hi @Spiros333,

The issue has been resolved in the new release, which is out now, and can be downloaded here - https://github.com/mollie/PrestaShop/releases/tag/4.4.3

Let us know if you have any other questions, and any feedback regarding the release!

--
Best regards,
Invertus Support team
