### ISSUE TITLE
When you downgrade/deinstall, database information is still there and gives issues

### ISSUE THREAD

**Issue by tajriba** [mollie/PrestaShop#457]
### Expected behavior
When deinstall mollie module, the previous database information is still there wat gives issues when using the downgraded version. 

### Actual behavior
- deinstall mollie plugin via modules in backend (vink ook module map aan)
- verwijderd niet de mollie db tabel(len) ps_mollie_payments 
- verwijderd niet alles met name like % % mollie in ps_configuration waardoor er oude configurations in blijven staat dat conflicten geeft. 

### Steps to reproduce the behavior
Installed version 4.4.0 
Downgrade to 4.2.2 

Wij konden uiteindelijk met veel moeite downgraden door de database informatie handmatig te verwijderen en zo de oude mollie versie weer te gebruiken. 

### Environment
* PrestaShop version: 1.7.5.0
<img width="263" alt="Schermafbeelding 2021-11-05 om 12 42 45" src="https://user-images.githubusercontent.com/68469531/140505410-1085f167-1e71-42d3-a5c0-336fdbacb9f6.png">

**Comment by Saimis777** [comment]
Hi @tajriba ,

We don't  delete all of it because if you do that will cause some problems like:

Deleting mollie_payments will cause old created orders to no longer work with Mollie, so no webhook updates, and it won't be able to refund, ship or cancel.
Deleting configuration will cause problems with custom order statuses and vouchers. So we can’t support it. If you want to downgrade in this case we think only removing reason from mollie_payments in database would fix it.

Let us know if you have any other questions!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hello @tajriba ,

We are marking ticket as resolved for now.

Please let us know if further help is needed, or if you will have any other questions.

--
Best regards,
Invertus Support team
