### ISSUE TITLE
not able to update mollie

### ISSUE THREAD

**Issue by Lela2HG** [mollie/PrestaShop#471]
### Expected behavior
 Not able to get the new update working. when updated to 4.4.2 I'm not allowed to make payment option useable. If I save, it will give me a 500 something went wrong error. 

And another issue. If updated to 4.4.1 it will still make an order even when transaction is cancelled.

### Actual behavior
should be able to save the payment options I want shown on the front of website. And no order should be made when transaction is cancelled. 

### Steps to reproduce the behavior
 Choose which payment option needs to be shown, then save. 
Cancel transaction and it is shown a cancelled order. 

### Environment
* PrestaShop version: 1.7.4.4 
* Mollie module version: 3.3.5, newer versions won't work for my shop
*  I'm not able to get in my php, since that part is being supervised by someone who knows about that.

**Comment by Saimis777** [comment]
Hi @Lela2HG ,

Thank you for the ticket.

Maybe you could send us your BO + FTP credentials to - support@invertus.eu?

Because we could not reproduce the issue from our end.

Looking forward to your reply!

--
Best regards,
Invertus Support team

**Comment by waschier-design** [comment]
We had similar issues a while ago. Problem where missing or old Database Tables of the module.
We solved the problems by:
1.) deinstall and delete module
2.) Delete all Tables related to mollie module manually (example via phpmyadmin) - because they were not deleted correctly in our project Database.
3.) Upload and install newest Version 
4.) View mollie tables in Databe and in case of missing tables / fields: Insert and Update Tables manually (example via phpmyadmin).

May this also fix your problems

**Comment by Lela2HG** [comment]
I will have a look tonight. Since it is the only payment option we have, I can't really try it out by day.. I'll let you know if this fixes the issues I had

**Comment by waschier-design** [comment]
Tried it - Mails are sent again :)
Fix is working :)

**Comment by Saimis777** [comment]
Hello,

I agree with @waschier-design (thanks for the information shared) , because as I see you've updated from 3.3.5 version which was refactored afterword.

Deleting the module, and the tables created by that version, and manually updating to the latest version might solve the case.

If not, we will be waiting for the credentials to check it out further!

--
Best regards,
Invertus Support team

**Comment by Saimis777** [comment]
Hi @Lela2HG ,

Did the steps help you?

--
Best regards,
Invertus Support team

**Comment by loonas** [comment]
Hi @Lela2HG,

Let us know once you're ready to continue with this!

For now, we will mark this issue as resolved.

--
Best regards,
Invertus Support team
