### ISSUE TITLE
Impossible to translate : "One or more fields are invalid."

### ISSUE THREAD

**Issue by AnatoleRozan** [mollie/PrestaShop#487]
### Actual behavior
There is no way to translate the error message : "One or more fields are invalid." in the Prestashop back-office.
It is however basic thing to do for a plugin development...

### Environment
* PrestaShop version: 1.7.7.0 
* Mollie module version: 4.4.3 
* PHP version: 7.1.26

**Comment by loonas** [comment]
Hi there, Anatole, I hope that you are doing well!

Could you please provide more information regarding the issue? Screenshots and expected behavior would be highly appreciated, as it would help us investigate.

Let us know!

Best regards,
Invertus Support team

**Comment by loonas** [comment]
Hi @AnatoleRozan,

Upon further checking with the team, we were able to find which place had this issue and we have forwarded the information to our developer.
We will keep you updated about the situation!

Best regards,
Invertus Support team

**Comment by loonas** [comment]
Hi @AnatoleRozan,

Our developer has looked into this issue and removed the error message, as it is returned from the API and cannot be translated.
You can find the fixed version of the module [here](https://we.tl/t-eCWYesdZwf).

Let us know how it goes!

Best regards,
Invertus Support team

**Comment by AnatoleRozan** [comment]
Thanks. But you should add a message, it is a standard for a payment form...

**Comment by loonas** [comment]
Thank you for your reply @AnatoleRozan,

We have checked this with the developer, and at the moment, it is not possible to translate the error message as it is returned from the API. Due to this, it has been removed completely.

Let me know if you have any further questions!

Best regards,
Invertus Support team

**Comment by loonas** [comment]
Hi there @AnatoleRozan,

Just wanted to follow up regarding this with you - the reported message "One or more fields are invalid" was removed due to the fact that it cannot be translated, as it is used for a different function.

Although, there is no need to worry - the other error message remains, which covers the standard and can also be translated as well: 
![image (3)](https://user-images.githubusercontent.com/30753843/146377700-346d5b3f-533e-4554-97c2-5f6492b479b4.png)
Please let me know if anything else seems to be unclear or if you have any further doubts!

Best regards,
Invertus Support team

**Comment by loonas** [comment]
Hi @AnatoleRozan,

Let us know once you're ready to continue with this!

For now, we will mark this issue as resolved.

--
Best regards,
Invertus Support team
