### ISSUE TITLE
Show order reference in payment description

### ISSUE THREAD

**Issue by yavuzaydin** [mollie/PrestaShop#56]
By default the order ID is shown in the payment description. Is it possible to add the order reference as a variable?

![image](https://user-images.githubusercontent.com/13795916/40770229-602e5f4a-64ba-11e8-890b-3130872af33f.png)

We want to show "Order OR04278" instead of "Order 12456" as description.

**Comment by yavuzaydin** [comment]
![image](https://user-images.githubusercontent.com/13795916/40770218-531c58e8-64ba-11e8-9489-e44068747092.png)

**Comment by snowycatsoftware** [comment]
Hi @yavuzaydin ,

The Cart ID is the default which is shown in the description. Because the Order ID and Reference are created after the payment has been completed, they can not be sent to Mollie beforehand. And a second call to Mollie to update this, can not be made. We tried to create a workaround for this a few months ago, but as stated, the way PrestaShop creates orders, it can not be done.

If we do find a proper way to establish this, it will be implemented in the Mollie module. We will close this issue for now.

Kind regards

**Comment by snowycatsoftware** [comment]
This suggestion has been added to the Mollie module version 3.3.0 and up. You can now add the order reference {order.reference} to the checkout description.

Kind Regards

**Comment by DaniWinter** [comment]
Whenever I use order.reference it stays empty in the payment description. Prestashop 1.6.1.23

**Comment by firstred** [comment]
Do you use the Payments API or the Orders API?

**Comment by firstred** [comment]
Looks like the order reference wasn't always being passed when using the Payments API. You can apply this change to fix it: https://github.com/mollie/PrestaShop/commit/8dc0786222eb70795e926c434e81b6b399a508dc

**Comment by DaniWinter** [comment]
@firstred Great, I was indeed using the Payments API

**Comment by firstred** [comment]
Or you can try this new build which includes even more fixes: 
[mollie-v3.3.2-beta.10.zip](https://github.com/mollie/PrestaShop/files/2629262/mollie-v3.3.2-beta.10.zip)

**Comment by firstred** [comment]
Does that solve it for you?

**Comment by DaniWinter** [comment]
@firstred Yes, thanks!

**Comment by firstred** [comment]
Great, thanks for letting us know!
