### ISSUE TITLE
New names/aliases in Mollie::methods

### ISSUE THREAD

**Issue by muyncky** [mollie/PrestaShop#58]
Hi,

Thanks for the frequent updates!

I was wondering the implications of the changes in the static array `$methods`. Currently it contains:
```
    /** @var array $methods */
    public static $methods = array(
        'banktransfer' => 'Bank',
        'belfius '     => 'Belfius',
        'bitcoin '     => 'Bitcoin',
        'creditcard'   => 'Credit Card',
        'directdebit'  => 'Direct Debit',
        'eps'          => 'EPS',
        'giftcard'     => 'Giftcard',
        'giropay'      => 'Giropay',
        'ideal'        => 'iDEAL',
        'inghomepay '  => 'ING Homepay',
        'kbc'          => 'KBC',
        'bancontact'   => 'Bancontact',
        'paypal'       => 'PayPal',
        'paysafecard'  => 'Paysafecard',
        'sofort'       => 'Sofort Banking',
    );
```

Two question:
1. The is a space at the end of the string `'belfius '` and `'bitcoin '`, is this correct?
2. If we change one of the names, what are the implications? For example: `'banktransfer' => 'Bankoverschrijving'`

Thank you for your time.

**Comment by snowycatsoftware** [comment]
Hi @muyncky ,

Thank you for pointing this out to us! If you want to alter the name of a payment method, the best way is to adjust the translations. If you open the config page of the Mollie module, you will see the "translations" button on the top-right of your screen. Choose Dutch. Underneath the "Module mollie" translation column, you will find the field for translationg banktransfer.

We updated the mollie.php file to fix the whitespace. We will release a new version in the near future. We are currently working on a new upgrade so this will be fixed in the new release as well.

We will close this issue for now. If you have any more questions, you can still post them in this issue.

Kind Rgards

**Comment by muyncky** [comment]
Hi @snowycatsoftware,

If we translate it, will this translation also appear in the `orders` tabel, like in the example:
![image](https://user-images.githubusercontent.com/17008327/41775240-76f10226-7623-11e8-86fa-2c8a1ca919d0.png)

**Comment by snowycatsoftware** [comment]
Hi @muyncky ,

Which version of prestashop are you currently using? Because these fields should already be translated automatically.

Regards

**Comment by muyncky** [comment]
We want the payment method not to change in the order. There is a webservice who uses, for example, `banktransfer` as a reference. It's therefor important that this remains so.

PrestaShop version: 1.6.0.14
