### ISSUE TITLE
Payment methods within Mollie should be separate payment methods within the backend

### ISSUE THREAD

**Issue by yavuzaydin** [mollie/PrestaShop#69]
Currently Mollie is regarded as a single payment method. Because of this it's impossible to do restrictions based on countries for instance.

Let's say we want to enable iDeal only for Dutch customers and Bancontact, KBC/CBC, Belfius and ING Home'Pay only for Belgian customers we can't do this.

![image](https://user-images.githubusercontent.com/13795916/46808554-e8c22600-cd6c-11e8-95a8-d4cfa57ed779.png)

**Comment by snowycatsoftware** [comment]
HI @yavuzaydin,

This feature won't be available in the coming update, but it will be implemented in the next update.

We will keep this issue open untill this feature has been implemented.

Kind Regards

**Comment by yavuzaydin** [comment]
OK, any ETA? I'm unfamiliar with your release schedule :)

**Comment by firstred** [comment]
We're not sure, yet. We'll let you know as soon as we have an ETA.

**Comment by firstred** [comment]
Hi @yavuzaydin 

This feature has been scheduled for February 2019.

Instead of using the Payment Settings page we are going to add a country list to the module's configuration page itself, since we are unable to release multiple versions of the module in PrestaShop's official store. This way you can still set country restrictions on payment methods.

**Comment by yavuzaydin** [comment]
The restrictions per country was only one of the examples. But there are lots of stuff which expect those payment methods to be separate. One of the other real-world use cases for us is the option to add a payment fee per payment method.

I still would love to see if you could make the payment methods separate payment methods in the backend.

If that is no option please add the ability to add payment fees per payment method. It would be nice to have the option to add an absolute or percentage based payment fee per payment method. If you want me to create a new issue for this let me know.

**Comment by firstred** [comment]
Adding a payment fee is no longer allowed under the new PSD2 legislation (more info: https://www.internetkassa.nu/webshops-geen-betaaltoeslagen-doorberekenen-consumenten/ 🇳🇱). As it is already in effect in a few EU countries, we have taken decided to take this feature off the roadmap.

Fees are still allowed for payment methods such as Klarna, which is what we will support in the future. See https://github.com/mollie/PrestaShop/issues/72 for more info).

**Comment by yavuzaydin** [comment]
PayPal is also excluded from PSD2 and creditcard transactions (which are a not only a payment instrument but also an insurance) is very complicated. I don't think this will ever happen or be accepted unless the percentage based transaction fees which are charged by you are off the table.

**Comment by firstred** [comment]
Only since 1.7 PrestaShop has made some progress towards a list of `paymentOptions` per payment module, but the architecture still does not handle them as separate methods. PrestaShop is unclear about their future plans with payment options.

1.6 and lower only allow to print some HTML per payment module, making it impossible to see them as separate methods. Providing completely separate modules (like Sisow does) would have to be renegotiated with the PrestaShop Addons team first as we are currently not allowed to release modules like that.

**Comment by willemstuursma** [comment]
Pff, that's annoying. Is the current approach the way all payment service providers handle this @firstred ?

**Comment by firstred** [comment]
Yes, unfortunately.

**Comment by margud** [comment]
Country restriction feature for each payment method was added in new [3.4.3](https://github.com/mollie/PrestaShop/releases/tag/3.4.3) release.
