### ISSUE TITLE
Surcharge for customers using Klarna

### ISSUE THREAD

**Issue by Huisdierdirect** [mollie/PrestaShop#72]
I like to add a surcharge for customers using Klarna. At the moment there is no possibility to add an extra fee for any of the payment methodes
Will there be a possibility in the future ? If not, do you have any suggestions how to do it myself ?
 

### Environment
* PrestaShop version: 1.6.1.1..
* Mollie module version: 3.30.0

**Comment by snowycatsoftware** [comment]
Hi @Huisdierdirect ,

We can not add this feature // your request to the Mollie module. The new PSD2 guidelines state merchants can not charge consumers for (card // creditcard // SEPA) payment methods. Even though Klarna is a factering company, in the end people pay by the abovementioned methods, which is not in line with the PSD2 guidelines.

You could eighter pass on these costs to the products by upping them by a (minute) percentage, or hire a webdeveloper to add this custom feature.

Kind Regards

**Comment by snowycatsoftware** [comment]
Hi @Huisdierdirect ,

We have re-opened this issue. Please ignore my last comment untill further notice. We did some more investigating concerning this matter. We will provide you with more information as soon as possible.

Kind Regards

**Comment by firstred** [comment]
Hi @Huisdierdirect 

This feature has been scheduled for March 2019 (version 3.5.0). It will allow you to set a fee for Klarna up to €1,95 (fixed) per transaction.

**Comment by Apury** [comment]
> Hi @Huisdierdirect
> 
> This feature has been scheduled for March 2019 (version 3.5.0). It will allow you to set a fee for Klarna up to €1,95 (fixed) per transaction.

Will the fee only be possible to be added to Klarna or more payment options?

In particular I'm looking at paypal here. 2,49% + up to 0,45cents + another 3.30% for cross border transactions equals in ~0.45€ + 5.79% excluding paypals .. "intersting" currency exchange rates. 

Which frankly makes it a pain to just throw roughly 6% at paypal.

**Comment by Torrentus** [comment]
This is the main reason we don't provide Paypal in our shop. I would really appreciate it if this functionality would be broader available then just for Klarna.

**Comment by firstred** [comment]
PayPal's User Agreement by default does not allow you to add a surcharge, unless you have successfully negotiated different terms, but I haven't heard of any such cases among PrestaShoppers.

**Comment by Torrentus** [comment]
"If you enable your customers to pay you with PayPal, you shall treat PayPal’s payment mark at least at par with other payment methods offered. PayPal does not encourage surcharging because it is a commercial practice that can penalise the consumer and create unnecessary confusion, friction and abandonment at checkout."

Does not encourage is something else than does not allow in my opinion.

**Comment by firstred** [comment]
We've been in touch with a few module developers to see if we can still make it happen, one way or another. Official support is still going to be tricky, so this might actually be an alternative that works for all. As soon as we have more information, we'll share it here!

**Comment by yavuzaydin** [comment]
A surcharge for an insurance (that is what the fees for PayPal and Credit Cards are) are feasible and absolutely legal. Since issue #69 is not possible on the short term we would need the ability to setup a surcharge for different payment methods.

I would like to suggest to change the title to something like "Surcharge per payment method" or something like that.

Could we also get an update?

**Comment by Huisdierdirect** [comment]
Hello,

Why is this closed ? As fas as I know it is still not solved.

regards
Jan /


Op 18-9-2019 om 15:09 schreef margud:
