### ISSUE TITLE
No Credit Slip on refund

### ISSUE THREAD

**Issue by svmt** [mollie/PrestaShop#79]
Since refund or partial refund does not generate any Credit Slip i've being generating those Cretid slips on my own but with the change to OrderAPI i have troubles to understand the logic how OrderAPI orderline ID is generated or related to PrestaShop OrderDetail row ID and if there is any link in between at all.

![2018-11-09](https://user-images.githubusercontent.com/19215202/48253744-5d3dc280-e408-11e8-99d0-04350ddbe5a1.png)

**Comment by firstred** [comment]
Hi @svmt 

The orderline IDs is generated on the Mollie servers. There is no relation between those order lines and PrestaShop's since you can't directly map the two. PrestaShop's order lines support all rounding methods whereas Mollie's is limited to item rounding only. You sometimes can see a conversion being made between the two.

**Current workaround:**
For now it looks like the name is the only direct relation between the two, since we can't push the `id_order_detail` field to the Mollie API. You can narrow down the results by taking the order reference from the Mollie Order object, but this still is still prone to duplicate name problems.

**Possible future solution:**
I wonder how many characters the SKU field can hold. We could fill it with `id_product`, `id_product_attribute`, EAN13, UPC, ISBN, `reference` and `supplier_reference`, separated by a special character, so there are plenty of fields to match order lines. The `id_order_detail` ID is unkown at the time of pushing the order info to the Mollie API, because it is just a cart at that moment and converted afterwards.

**Comment by svmt** [comment]
Hi @firstred 

Yes i understand the issue that order_details is created on return after payment is complete and it is not know before. 

In regard of setting up your SKU filed maybe just to use id_product and id_product_attribute separated by some special character. I think it will be unique and that would make it easy to find back linked order_detail row

**Comment by firstred** [comment]
We're going to make sure the next patch version (3.3.2) sends `id_product`, `id_product_attribute` and `id_customization` in the `sku` field, separated by a generic currency sign: [¤](https://theasciicode.com.ar/extended-ascii-code/generic-currency-sign-ascii-code-207.html)

**Comment by svmt** [comment]
Thank you that would help very much

**Comment by firstred** [comment]
You're welcome!
