### ISSUE TITLE
Some webhooks not firing resulting in status not being changed

### ISSUE THREAD

**Issue by semammerlaan** [mollie/PrestaShop#84]
### Expected behavior
Almost every payment gets through in our backend.
1 - 2 times a month the webhook is not firing, we don't see a log record for that specific order.

### Steps to reproduce the behavior
We don't know why some get through en some doesn't.

### Environment
* PrestaShop version: 1.6.1.3 (replace this with the full version you are using).
* Mollie module version: 1.2.6 (replace this with the full version you are using).

**Comment by snowycatsoftware** [comment]
Hi @semammerlaan ,

We don't have enough information in order to properly advice you. You're also using an outdated verson of the Mollie module which is no longer supported. If you prefer to use an older version (because your PS version is pretty outdated as well), it might be best to use the Mollie module v1.3.0 or v1.3.1 which you can download here:

https://github.com/mollie/PrestaShop/releases?after=v2.0.4

Because the module version you are using is no longer in active development, we are closing this issue.

Kind Regards
