### ISSUE TITLE
Mollie module stopped working

### ISSUE THREAD

**Issue by Frankyet** [mollie/PrestaShop#890]
When in the checkout Ideal or Bancontact from Mollie module is selected and hit the pay button there will be a mesages to the custumor, "Something went wrong while creating the payment. Please contact our customer service."
![image](https://github.com/mollie/PrestaShop/assets/22242384/c72bfec7-3e03-45b8-9b4e-0603e9e31099)

The status page form Mollie don't gave any issues
https://status.mollie.com
(9 and 10 march)

Environment
* PrestaShop version: 8.1.2 
* Mollie module version: v6.0.5, tried also the 6.1.0 beta- same issue
* PHP version: 8.1

Activated now at the moment the pay.nl payment module and that is working correctly.

someting wrong at Mollie?

**Comment by justelis22** [comment]
Hi @Frankyet,

We were not able to recreate the issue in our demo environment, everything seems to be working fine.
Can you share the back office and FTP credentials with us? Please send that to your email at support@invertus.eu.

Waiting for your information!

Best regards,
Invertus Support team.

**Comment by justelis22** [comment]
Hi @Frankyet,

Thanks for clarifying, yes, most likely the issue was with the Mollie system itself and not PrestaShop in that case. Glad to hear that it is working now!

Are those issues that you are facing can be recreated? As we haven't received any similar complaints it is difficult to identify the root cause.
We would love to keep you as our customer!

Best regards,
Invertus Support team.
