### ISSUE TITLE
Subscription mechanism is limited to one product per command

### ISSUE THREAD

**Issue by zorrobiwan** [mollie/PrestaShop#983]
### Expected behavior
Client should be able to subscribe to more than one product per order

### Actual behavior
If you try to add a second product (with subscription) to the basket, an error message is displayed
<img width="248" alt="image" src="https://github.com/user-attachments/assets/b27392e9-5306-4655-b0f3-213d2828045d">

> Please note: Only one subscription product can be added to the cart at a time.

### Steps to reproduce the behavior
Add a first product (with subscription) to the basket, then try to another one :)

### Environment

- PrestaShop version: 1.7.7.6
- Mollie module version: 6.2.2
- PHP version: 7.3.31-1~deb10u7

So it's coded by design. Any plan to support multiple subscription in one (first) initial order ?

**Comment by justelis22** [comment]
Hi there @zorrobiwan,

We will check this case and I will get back to you as soon as more details.

Thank you for your patience!

--
Best Regards,
Invertus Support team.

**Comment by justelis22** [comment]
Hi there @zorrobiwan, thanks for waiting!

We have analyzed the functionality and refined it with the Mollie team.

Mollie API accepts one product as a subscription, so we have validation on the PrestaShop to match this behavior. 

That being said, this is how subscriptions work, and it is expected behavior. Currently, we are not planning any changes.

If you have any other questions, please let me know!

Best Regards,
Invertus Support team.
